VERSION_MAJOR = 0
VERSION_MINOR = 1
VERSION_PATCH = 0

VS_SRC = include/version.h.in
VS_OBJ = $(PATHD)/version.h

version: $(VS_OBJ)

$(VS_OBJ): $(VS_SRC) Makefile
	$(COPY) $(VS_SRC) $(VS_OBJ)
	sed -i "s/@CMAKE_PROJECT_VERSION_MAJOR@/$(VERSION_MAJOR)/g" $(VS_OBJ)
	sed -i "s/@CMAKE_PROJECT_VERSION_MINOR@/$(VERSION_MINOR)/g" $(VS_OBJ)
	sed -i "s/@CMAKE_PROJECT_VERSION_PATCH@/$(VERSION_PATCH)/g" $(VS_OBJ)
